#!/bin/bash
# Quick Setup & Testing Guide for Payment System

echo "================================"
echo "Payment System - Quick Reference"
echo "================================"

echo ""
echo "📁 PROJECT STRUCTURE"
echo "---"
echo "Backend:"
echo "  ├── models/"
echo "  │   ├── Earning.ts          (Influencer earnings tracking)"
echo "  │   └── Payment.ts          (Brand payment tracking)"
echo "  ├── controllers/"
echo "  │   ├── earnings.controller.ts"
echo "  │   └── payments.controller.ts"
echo "  └── routes/"
echo "      ├── earnings.route.ts"
echo "      └── payments.route.ts"
echo ""
echo "Frontend:"
echo "  └── src/lib/api/"
echo "      ├── earnings.ts         (EarningsService)"
echo "      └── payments.ts         (PaymentsService)"
echo ""
echo "Pages:"
echo "  ├── app/influencer/earnings/page.tsx"
echo "  └── app/brand/payments/page.tsx"

echo ""
echo "🚀 BACKEND ENDPOINTS"
echo "---"
echo ""
echo "EARNINGS (Influencer Side)"
echo "  GET    /api/earnings/influencer/:influencerId"
echo "  GET    /api/earnings/influencer/:influencerId/summary"
echo "  GET    /api/earnings/:earningId"
echo "  POST   /api/earnings/"
echo "  PATCH  /api/earnings/:earningId/status"
echo "  GET    /api/earnings/campaign/:campaignId"
echo ""
echo "PAYMENTS (Brand Side)"
echo "  GET    /api/payments/brand/:brandId"
echo "  GET    /api/payments/brand/:brandId/summary"
echo "  GET    /api/payments/brand/:brandId/breakdown"
echo "  GET    /api/payments/:paymentId"
echo "  POST   /api/payments/"
echo "  PATCH  /api/payments/:paymentId/status"
echo "  GET    /api/payments/campaign/:campaignId"
echo "  POST   /api/payments/brand/:brandId/process"

echo ""
echo "💻 FRONTEND SERVICES"
echo "---"
echo ""
echo "import { earningsService } from '@/lib/api/earnings';"
echo "import { paymentsService } from '@/lib/api/payments';"
echo ""
echo "EarningsService Methods:"
echo "  • getInfluencerEarnings(influencerId, params?)"
echo "  • getInfluencerEarningsSummary(influencerId)"
echo "  • getEarningById(earningId)"
echo "  • createEarning(data)"
echo "  • updateEarningStatus(earningId, data)"
echo "  • getEarningsByCampaign(campaignId)"
echo ""
echo "PaymentsService Methods:"
echo "  • getBrandPayments(brandId, params?)"
echo "  • getBrandPaymentsSummary(brandId)"
echo "  • getPaymentMethodBreakdown(brandId)"
echo "  • getPaymentById(paymentId)"
echo "  • createPayment(data)"
echo "  • updatePaymentStatus(paymentId, data)"
echo "  • getPaymentsByCampaign(campaignId)"
echo "  • processPendingPayments(brandId, data)"

echo ""
echo "🔄 DATA FLOW"
echo "---"
echo "Campaign Complete → Create Earning → Create Payment → Process → Update Status"
echo ""
echo "Earning Statuses:"
echo "  pending → ready_for_payment → paid"
echo "         → failed"
echo ""
echo "Payment Statuses:"
echo "  pending → processing → completed"
echo "        → failed"

echo ""
echo "📝 QUICK START CODE"
echo "---"
echo ""
echo "1. Create Earning when Campaign Completes:"
echo "   const earning = await earningsService.createEarning({"
echo "     influencerId: 'user_123',"
echo "     campaignId: 'campaign_456',"
echo "     brandId: 'brand_789',"
echo "     amount: 1500,"
echo "     paymentMethod: 'direct'"
echo "   });"
echo ""
echo "2. Create Corresponding Payment:"
echo "   const payment = await paymentsService.createPayment({"
echo "     brandId: 'brand_789',"
echo "     influencerId: 'user_123',"
echo "     campaignId: 'campaign_456',"
echo "     earningId: earning.data._id,"
echo "     amount: 1500,"
echo "     paymentMethod: 'direct'"
echo "   });"
echo ""
echo "3. Get Influencer Earnings:"
echo "   const data = await earningsService.getInfluencerEarnings('user_123');"
echo ""
echo "4. Get Brand Payment Summary:"
echo "   const summary = await paymentsService.getBrandPaymentsSummary('brand_789');"
echo ""
echo "5. Process Payment:"
echo "   await paymentsService.updatePaymentStatus(paymentId, {"
echo "     status: 'completed',"
echo "     notes: 'Processed successfully'"
echo "   });"

echo ""
echo "⚙️ CONFIGURATION"
echo "---"
echo "Frontend API URL (environment variable):"
echo "  NEXT_PUBLIC_API_URL=http://localhost:8000"
echo ""
echo "Backend MongoDB:"
echo "  Collections: earnings, payments"
echo "  Auto-created with indexes"

echo ""
echo "🧪 TESTING CHECKLIST"
echo "---"
echo "□ Backend server running (npm run dev)"
echo "□ MongoDB connected"
echo "□ Create test earning record"
echo "□ Create test payment record"
echo "□ Update payment status"
echo "□ Verify earning status auto-updates"
echo "□ Test influencer earnings page loads"
echo "□ Test brand payments page loads"
echo "□ Test filtering and pagination"
echo "□ Test summary calculations"

echo ""
echo "🐛 DEBUGGING"
echo "---"
echo "Enable logging in services (uncomment console.log in actions)"
echo ""
echo "Common Issues:"
echo "  • 404: Endpoint not registered in server.ts"
echo "  • 500: MongoDB connection or model issue"
echo "  • CORS: Check origin in server.ts"
echo "  • Missing fields: Check required params in controller"

echo ""
echo "📚 DOCUMENTATION"
echo "---"
echo "  • PAYMENT_API_DOCS.md       - Complete API reference"
echo "  • IMPLEMENTATION_NOTES.md   - Implementation overview"
echo "  • PAYMENT_EXAMPLES.ts       - Usage examples"

echo ""
echo "================================"
echo "Ready to use! 🎉"
echo "================================"
